# path name definitions
MOVE_SQUARE = "move_square"
MOVE_TRIANGLE = "move_triangle"
MOVE_PARALLELOGRAM = "move_parallelogram"
MOVE_SEMICIRCLE = "move_semicircle"
MOVE_CIRCLE = "move_circle"
MOVE_DOWN_CIRCLE = "move_down_circle"
SQUARE = "square"
TRIANGLE = "triangle"
PARALLELOGRAM = "parallelogram"
SEMICIRCLE = "semicircle"
CIRCLE = "circle"
DOWN_CIRCLE = "down_circle"
CUBOID = "cuboid"
FOUR_CUBOID = "four_cuboid"

START_MESSAGE = "Modulation started"
FINISH_MESSAGE = "Modulation finished"
