# path name definitions
MOVE_SQUARE = "move_square"
MOVE_OPPOSITE_SQUARE = "move_opposite_square"
MOVE_TRIANGLE = "move_triangle"
MOVE_TRIANGLE_RIGHT = "move_triangle_right"
MOVE_PARALLELOGRAM = "move_parallelogram"
MOVE_PARALLELOGRAM_X = "move_parallelogram_x"
MOVE_PARALLELOGRAM_Y = "move_parallelogram_y"
MOVE_SEMICIRCLE = "move_semicircle"
MOVE_DOUBLE_SEMICIRCLE = "move_double_semicircle"
MOVE_CIRCLE = "move_circle"
MOVE_DOWN_CIRCLE = "move_down_circle"
SQUARE = "square"
OPPOSITE_SQUARE = "opposite_square"
TRIANGLE = "triangle"
TRIANGLE_RIGHT = "triangle_right"
PARALLELOGRAM = "parallelogram"
PARALLELOGRAM_X = "parallelogram_x"
PARALLELOGRAM_Y = "parallelogram_y"
SEMICIRCLE = "semicircle"
DOUBLE_SEMICIRCLE = "double_semicircle"
CIRCLE = "circle"
DOWN_CIRCLE = "down_circle"
CUBOID = "cuboid"
FOUR_CUBOID = "four_cuboid"

START_MESSAGE = "Modulation started"
FINISH_MESSAGE = "Modulation finished"
